// <auto-generated />
using System;
using GestionApiario.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionApiario.Migrations
{
    [DbContext(typeof(GestionApiariosContext))]
    [Migration("20251115134317_eliminacionProductoPorEnfermedad")]
    partial class eliminacionProductoPorEnfermedad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionApiario.Models.Alimento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioAlta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioBaja")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Codigo")
                        .HasName("PK__ALIMENTO__06370DAD793DF6FA");

                    b.ToTable("ALIMENTOS", (string)null);
                });

            modelBuilder.Entity("GestionApiario.Models.Apiario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Latitud")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Longitud")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioAlta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioBaja")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Codigo")
                        .HasName("PK__APIARIO__06370DADE50DDD3D");

                    b.ToTable("APIARIO", (string)null);
                });

            modelBuilder.Entity("GestionApiario.Models.Campaña", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int?>("Año")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioAlta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioBaja")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Codigo")
                        .HasName("PK__CAMPAÑA__06370DAD7B4D3DD6");

                    b.ToTable("CAMPAÑA", (string)null);
                });

            modelBuilder.Entity("GestionApiario.Models.Controle", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int?>("CantDeColmenas")
                        .HasColumnType("int");

                    b.Property<decimal?>("CantProducto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("CantidadAlimento")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("CodAlimento")
                        .HasColumnType("int");

                    b.Property<int?>("CodApiario")
                        .HasColumnType("int");

                    b.Property<int?>("CodCampaña")
                        .HasColumnType("int");

                    b.Property<int?>("CodEnfermedad")
                        .HasColumnType("int");

                    b.Property<int?>("CodProductos")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Obsevaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UsuarioAlta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioBaja")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Codigo")
                        .HasName("PK__CONTROLE__06370DADD3C8B4F3");

                    b.HasIndex("CodAlimento");

                    b.HasIndex("CodApiario");

                    b.HasIndex("CodCampaña");

                    b.HasIndex("CodEnfermedad");

                    b.HasIndex("CodProductos");

                    b.ToTable("CONTROLES", (string)null);
                });

            modelBuilder.Entity("GestionApiario.Models.Enfermedad", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioAlta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioBaja")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Codigo")
                        .HasName("PK__ENFERMED__06370DAD59FB3587");

                    b.ToTable("ENFERMEDAD", (string)null);
                });

            modelBuilder.Entity("GestionApiario.Models.Producto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioAlta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioBaja")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Codigo")
                        .HasName("PK__PRODUCTO__06370DAD5655F7E5");

                    b.ToTable("PRODUCTOS", (string)null);
                });

            modelBuilder.Entity("GestionApiario.Models.Controle", b =>
                {
                    b.HasOne("GestionApiario.Models.Alimento", "CodAlimentoNavigation")
                        .WithMany("Controles")
                        .HasForeignKey("CodAlimento")
                        .HasConstraintName("FK__CONTROLES__CodAl__59063A47");

                    b.HasOne("GestionApiario.Models.Apiario", "CodApiarioNavigation")
                        .WithMany("Controles")
                        .HasForeignKey("CodApiario")
                        .HasConstraintName("FK__CONTROLES__CodAp__5812160E");

                    b.HasOne("GestionApiario.Models.Campaña", "CodCampañaNavigation")
                        .WithMany("Controles")
                        .HasForeignKey("CodCampaña")
                        .HasConstraintName("FK__CONTROLES__CodCa__571DF1D5");

                    b.HasOne("GestionApiario.Models.Enfermedad", "CodEnfermedadNavigation")
                        .WithMany("Controles")
                        .HasForeignKey("CodEnfermedad")
                        .HasConstraintName("FK__CONTROLES__CodEn__59FA5E80");

                    b.HasOne("GestionApiario.Models.Producto", "CodProductosNavigation")
                        .WithMany("Controles")
                        .HasForeignKey("CodProductos")
                        .HasConstraintName("FK__CONTROLES__CodPr__5AEE82B9");

                    b.Navigation("CodAlimentoNavigation");

                    b.Navigation("CodApiarioNavigation");

                    b.Navigation("CodCampañaNavigation");

                    b.Navigation("CodEnfermedadNavigation");

                    b.Navigation("CodProductosNavigation");
                });

            modelBuilder.Entity("GestionApiario.Models.Alimento", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("GestionApiario.Models.Apiario", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("GestionApiario.Models.Campaña", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("GestionApiario.Models.Enfermedad", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("GestionApiario.Models.Producto", b =>
                {
                    b.Navigation("Controles");
                });
#pragma warning restore 612, 618
        }
    }
}
